// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDivciPfLhQoZ0jWqHmyoflLfdxMfeHIS0',
    appId: '1:653815068558:android:92bad7329b39290c1cd6df',
    messagingSenderId: '653815068558',
    projectId: 'simplelive-29c42',
    storageBucket: 'simplelive-29c42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhxKl6wrFvqKRxs3dGsVi5z7pLbcwJe6I',
    appId: '1:653815068558:ios:c2c3555d6d3e15171cd6df',
    messagingSenderId: '653815068558',
    projectId: 'simplelive-29c42',
    storageBucket: 'simplelive-29c42.firebasestorage.app',
    iosBundleId: 'com.xycz.simple-live',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhxKl6wrFvqKRxs3dGsVi5z7pLbcwJe6I',
    appId: '1:653815068558:ios:e63421fc90b880331cd6df',
    messagingSenderId: '653815068558',
    projectId: 'simplelive-29c42',
    storageBucket: 'simplelive-29c42.firebasestorage.app',
    iosBundleId: 'com.xycz.simpleLiveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1PZlwQN93McLoT5MOeGsvwLytdHmJTjw',
    appId: '1:653815068558:web:4430375d4e92110d1cd6df',
    messagingSenderId: '653815068558',
    projectId: 'simplelive-29c42',
    authDomain: 'simplelive-29c42.firebaseapp.com',
    storageBucket: 'simplelive-29c42.firebasestorage.app',
    measurementId: 'G-L42J5K68KV',
  );
}
